version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3005:3005"
    env_file:
      - ./frontend/.env
