export const Users = [
    {
        "employeeCode": "EMP001",
        "username": "superadminUser",
        "password": "SuperAdmin@123",
        "role": "superadmin",
        "department": "software",
        "email": "superadmin@example.com",
        "contact": "+911234567890",
        "accountType": true,
        "status": "active",
        "dateOfJoining": "2024-01-10",
        "createdBy": "system",
        "profileImage": "https://example.com/images/superadmin.jpg"
    },
    {
        "employeeCode": "EMP002",
        "username": "adminUser",
        "password": "Admin@123",
        "role": "admin",
        "department": "business",
        "email": "admin@example.com",
        "contact": "+911234567891",
        "accountType": true,
        "status": "active",
        "dateOfJoining": "2024-02-05",
        "createdBy": "superadminUser",
        "profileImage": "https://example.com/images/admin.jpg"
    },
    {
        "employeeCode": "EMP003",
        "username": "hrUser",
        "password": "HR@123",
        "role": "hr",
        "department": "hr",
        "email": "hr@example.com",
        "contact": "+911234567892",
        "accountType": false,
        "status": "active",
        "dateOfJoining": "2024-03-15",
        "createdBy": "adminUser",
        "profileImage": "https://example.com/images/hr.jpg"
    },
    {
        "employeeCode": "EMP004",
        "username": "managerUser",
        "password": "Manager@123",
        "role": "manager",
        "department": "financial",
        "email": "manager@example.com",
        "contact": "+911234567893",
        "accountType": true,
        "status": "active",
        "dateOfJoining": "2024-04-01",
        "createdBy": "hrUser",
        "profileImage": "https://example.com/images/manager.jpg"
    },
    {
        "employeeCode": "EMP005",
        "username": "employeeUser",
        "password": "Employee@123",
        "role": "employee",
        "department": "iot",
        "email": "employee@example.com",
        "contact": "+911234567894",
        "accountType": false,
        "status": "active",
        "dateOfJoining": "2024-05-20",
        "createdBy": "managerUser",
        "profileImage": "https://example.com/images/employee.jpg"
    },
    {
        "employeeCode": "EMP006",
        "username": "internUser",
        "password": "Intern@123",
        "role": "intern",
        "department": "software",
        "email": "intern@example.com",
        "contact": "+911234567895",
        "accountType": false,
        "status": "active",
        "dateOfJoining": "2024-06-12",
        "createdBy": "employeeUser",
        "profileImage": "https://example.com/images/intern.jpg"
    },
    {
        "employeeCode": "EMP007",
        "username": "ceoUser",
        "password": "CEO@123",
        "role": "ceo",
        "department": "business",
        "email": "ceo@example.com",
        "contact": "+911234567896",
        "accountType": true,
        "status": "active",
        "dateOfJoining": "2024-07-25",
        "createdBy": "superadminUser",
        "profileImage": "https://example.com/images/ceo.jpg"
    }
]

